config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users
  resources :otpforms
  resources :customers
  root "customers#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/otpforms_controller.rb
class OtpformsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_otpform, only: [:show, :edit, :destroy]

  # GET /otpforms
  # GET /otpforms.json
  def index
    @otpforms = current_user.otpforms
  end

  # GET /otpforms/1
  # GET /otpforms/1.json
  def show
    @otpform = Otpform.find(params[:id])
  end

  # GET /otpforms/new
  def new
    @otpform = Otpform.new
    
    @otpform.user_id = current_user.id
  end

  # GET /otpforms/1/edit
  def edit 
  end

  # POST /otpforms
  # POST /otpforms.json
  def create
    @otpform = Otpform.new(otpform_params)
    @otpform.user_id = current_user.id
    respond_to do |format|
      @customer = Customer.where(mobile: @otpform.mobile).first
      if(@otpform.otp_received==@customer.otpsent)
        @customer.update_attributes(verified: true)
        if ((@otpform.save) && (@customer.verified))
          format.html { redirect_to @otpform, notice: 'Otpform was successfully created' }
          format.json { render :show, status: :created, location: @otpform }
        else
          format.html { render :new }
          format.json { render json: @otpform.errors, status: :unprocessable_entity }
        end
      else
        @customer.update_attributes(verified: false)
        format.html { render :new,notice: "otp verification is been improper" }
        format.json { render json: @otpform.errors, status: :unprocessable_entity } 
      end  
    end
  end

  # PATCH/PUT /otpforms/1
  # PATCH/PUT /otpforms/1.json
  def update
    @otpform = Otpform.find(params[:id])
     
    @otpform.update_attributes(otpform_params)
    respond_to do |format|
      @customer = current_user.customers.where(mobile: @otpform.mobile).first 
      if(@otpform.otp_received==@customer.otpsent)
        
        @customer.update_attributes(verified: true)
        if ((@otpform.save) && (@customer.verified))
          format.html { redirect_to @otpform, notice:'Otpform was successfully created' }
          format.json { render :show, status: :created, location: @otpform }
        else
          
          format.html { render :new }
          format.json { render json: @otpform.errors, status: :unprocessable_entity }
        end
      else
        
        format.html { render :new, notice: 'Otpform has received unsuccessful parameters'}
        format.json { render json: @otpform.errors, status: :unprocessable_entity } 
      end
    end
  end

  # DELETE /otpforms/1
  # DELETE /otpforms/1.json
  def destroy
    @otpform.destroy
    respond_to do |format|
      format.html { redirect_to otpforms_url, notice: 'Otpform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_otpform
      @otpform = Otpform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def otpform_params
      params.require(:otpform).permit(:mobile, :otp_received,:user_id)
    end
end

app/helpers/otpforms_helper.rb
module OtpformsHelper
end

app/views/otpforms/_form.html.erb
<%= form_with(model: otpform, local: true) do |form| %>
  <% if otpform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(otpform.errors.count, "error") %> prohibited this otpform from being saved:</h2>

      <ul>
      <% otpform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :otp_recived %>
    <%= form.text_field :otp_received %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/otpforms/edit.html.erb
<h1>Editing Otpform</h1>

<%= render 'form', otpform: @otpform %>

<%= link_to 'Show', @otpform %> |
<%= link_to 'Back', otpforms_path %>

app/views/otpforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Otpforms</h1>

<table>
  <thead>
    <tr>
      <th>Mobile</th>
      <th>Otp received</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @otpforms.each do |otpform| %>
      <tr>
        <td><%= otpform.mobile %></td>
        <td><%= otpform.otp_received %></td>
        <td><%= link_to 'Show', otpform %></td>
        <td><%= link_to 'Edit', edit_otpform_path(otpform) %></td>
        <td><%= link_to 'Destroy', otpform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "customers",customers_path%>
<%= link_to 'New Otpform', new_otpform_path %>

app/views/otpforms/new.html.erb
OTP HAS TO BE VERIFIED TO CONTINUE FURTHER
<h1>New Otpform</h1>
<%= render 'form', otpform: @otpform %>
<%= link_to 'Back', otpforms_path %>

app/views/otpforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mobile:</strong>
  <%= @otpform.mobile %>
</p>

<p>
  <strong>Otp received:</strong>
  <%= @otpform.otp_received %>
</p>
OTP verification is done successfully 
<%= link_to 'Edit', edit_otpform_path(@otpform) %> |
<%= link_to 'Back', otpforms_path %>